// <auto-generated />
using BigBang_Assessment_26_5_23_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigBang_Assessment_26_5_23_.Migrations
{
    [DbContext(typeof(XYZHotelDbContext))]
    partial class XYZHotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.Employee_XYZHotels", b =>
                {
                    b.Property<string>("EHID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("XYZHotelHotelId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EHID");

                    b.HasIndex("XYZHotelHotelId");

                    b.ToTable("Employee_XYZHotels");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.Employees", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeDOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeDOJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmployeePasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("EmployeePasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EmployeeQualifications")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.HotelAddress", b =>
                {
                    b.Property<string>("HotelAddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelAddressId");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelAddress");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.Login_Logs", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.ToTable("Login_Logs");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.Rooms", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("XYZHotelIdHotelId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoomId");

                    b.HasIndex("XYZHotelIdHotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("UserPasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("UserPasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.XYZHotels", b =>
                {
                    b.Property<string>("HotelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HotelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.Employee_XYZHotels", b =>
                {
                    b.HasOne("BigBang_Assessment_26_5_23_.Models.XYZHotels", "XYZHotel")
                        .WithMany("Employee_XYZHotels")
                        .HasForeignKey("XYZHotelHotelId");

                    b.Navigation("XYZHotel");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.HotelAddress", b =>
                {
                    b.HasOne("BigBang_Assessment_26_5_23_.Models.XYZHotels", "Hotel")
                        .WithMany("HotelAddresses")
                        .HasForeignKey("HotelId");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.Rooms", b =>
                {
                    b.HasOne("BigBang_Assessment_26_5_23_.Models.XYZHotels", "XYZHotelId")
                        .WithMany("Rooms")
                        .HasForeignKey("XYZHotelIdHotelId");

                    b.Navigation("XYZHotelId");
                });

            modelBuilder.Entity("BigBang_Assessment_26_5_23_.Models.XYZHotels", b =>
                {
                    b.Navigation("Employee_XYZHotels");

                    b.Navigation("HotelAddresses");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
